#!/bin/bash

DIR=`pwd`

function l {
	TARGET=$HOME/$2
	if [ ! -e "$TARGET" ]; then
		ln -s "$DIR/$1" "$TARGET"
	fi
}

echo "Install packages"
sudo apt-get update
sudo apt-get install curl zsh i3 dunst vim htop

echo "Setup Shell colors"
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

echo "Setup theme"
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
sudo apt-get install arc-theme

sudo add-apt-repository ppa:numix/ppa
sudo apt-get install numix-icon-theme-circle

echo "Install PowerlineFonts"
git clone --depth=1 git@github.com:powerline/fonts.git /tmp/fonts
bash /tmp/fonts/install.sh

echo "Install Oh My Zsh"
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
rm $HOME/.zshrc # Remove default config file so the setup config file can be linked

echo "Install Google Chrome"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get install google-chrome-stable

echo "Setup vim"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo "Linking dotfiles to the correct location..."

mkdir -p $HOME/bin
mkdir -p $HOME/.config/{dunst,xfce4/terminal}
mkdir -p $HOME/.i3

l i3/config .i3/config
l i3/i3status.conf .i3status.conf
l bin/after_xfsettingsd bin/after_xfsettingsd
l bin/random_background bin/random_background
l dunst/dunstrc .config/dunst/dunstrc
l vim/vimrc .vimrc
l zsh/zshrc .zshrc
l xfce4/terminal/terminalrc .config/xfce4/terminal/terminalrc
l gitconfig .gitconfig
l gitignore .gitignore

echo "Done."
