#!/bin/bash

DIR=`pwd`

function l {
	TARGET=$HOME/$2
	if [ ! -e "$TARGET" ]; then
		ln -s "$DIR/$1" "$TARGET"
	fi
}

echo "Install packages"
sudo add-apt-repository ppa:ondrej/php5-5.6 -y
sudo add-apt-repository ppa:numix/ppa -y
sudo apt-get update
sudo apt-get install curl zsh i3 dunst vim htop feh virtualbox vagrant -y

echo "Install php"
sudo apt-get install php5 php5-cli php5-curl php5-mcrypt php5-xdebug php5-intl php5-sqlite php5-json php5-common php5-dev php-pear -y
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

echo "Install nvm"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

echo "Setup Shell colors"
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

echo "Setup theme"
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
sudo apt-get install arc-theme numix-icon-theme-circle -y

echo "Install PowerlineFonts"
git clone --depth=1 git@github.com:powerline/fonts.git /tmp/fonts
bash /tmp/fonts/install.sh

echo "Install Oh My Zsh"
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
rm $HOME/.zshrc # Remove default config file so the setup config file can be linked

echo "Install Google Chrome"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get install google-chrome-stable -y

echo "Setup vim"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

echo "Install NodeJS"
curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install nodejs -y

echo "Install Sublime Text"
curl -o /tmp/st.deb http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_amd64.deb
sudo dpkg -i /tmp/st.deb
mkdir -p $HOME/.config/sublime-text-3/{Packages,Installed\ Packages}
rm -r $HOME/.config/sublime-text-3/Packages/User

curl -o $HOME/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package https://sublime.wbond.net/Package%20Control.sublime-package

echo "Linking dotfiles to the correct location..."

mkdir -p $HOME/bin
mkdir -p $HOME/.config/{dunst,i3blocks,xfce4/terminal}
mkdir -p $HOME/.i3

l i3/config .i3/config
l i3/i3status.conf .i3status.conf
l i3blocks/config .config/i3blocks/config
l bin/after_xfsettingsd bin/after_xfsettingsd
l bin/random_background bin/random_background
l dunst/dunstrc .config/dunst/dunstrc
l vim/vimrc .vimrc
l zsh/zshrc .zshrc
l xfce4/terminal/terminalrc .config/xfce4/terminal/terminalrc
l gitconfig .gitconfig
l gitignore .gitignore
l sublime-text/User .config/sublime-text-3/Packages/User

echo "Done."
