#!/bin/bash

DIR=`pwd`

function l {
	TARGET=$HOME/$2
	if [ ! -e "$TARGET" ]; then
		ln -s "$DIR/$1" "$TARGET"
	fi
}

echo "Install Oh My Zsh"
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

echo "Linking dotfiles to the correct location..."

l i3/config .i3/config
l i3/i3status.conf .i3status.conf
l bin/after_xfsettingsd bin/after_xfsettingsd
l bin/random_background bin/random_background
l dunst/dunstrc .config/dunst/dunstrc
l vim/vimrc .vimrc
l zsh/zshrc .zshrc
l xfce4/terminal/terminalrc .config/xfce4/terminal/terminalrc

echo "Done."
